media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: index
    label: Index
    type: file
    path: index.md   
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: releaseCode, label: Release Code, type: string }
      - { name: duration, label: Duration, type: string }
      - { name: coverVideo, label: Cover video, type: video }
      - { name: videoPoster, label: Video poster image, type: image }
      - { name: introText, label: Intro Text, type: rich-text },
      - { name: infoBlock1, label: "Info Block 1", type: string, description: "eg. details about the number of tracks, singles, and bonus content included in the release" }
      
      - { name: infoBlock2, label: "Info Block 2", type: string, description: "eg. information about the available formats and delivery method of the album" }
      - { name: infoBlock3, label: "Info Block 3", type: text, description: "eg. explanation of how purchases directly support future releases etc.." }
      - { name: proceedsText, label: Proceeds Text, type: rich-text },
      - { name: buyButtonText, label: Buy button text, type: string }
      - { name: buyButtonLink, label: Buy button link, type: string }
      - { name: price, label: Price, type: string }
      - { name: creditsText, label: Credits, type: string },
      - { name: copyrightBody, label: Copyright body, type: text, description: "for the copyright field in the bottom" }
      - { name: copyrightEndText, label: Copyright end text, type: text, description: "for the final line of the copyright" }
      - { name: body, label: Content, type: rich-text }